title: The Millennial Tao
author: kywang
email: kywang@millennialtao.com
description: > # this means to ignore newlines until "baseurl:"
Welcome to my blog.
# social links
github_username:  karen-wang # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
theme: minima
