title: The Millennial Tao
# author: kywang
email: kywang@millennialtao.com
description: Short essays on simple living.
# social links
# github_username:  karen-wang # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
theme: minima
